language: java
services:
  - docker
script:
  - pushd ci
  - ccrypt -d -K $AWS_CRYPT_KEY aws.pem.cpt >/dev/null 2>&1
  - cat aws.pem
  - popd
  - echo $DOCKERHUB_ACCESS_TOKEN | docker login --username avanux --password-stdin
  - mvn package -B -Ptravis,web
  - cd docker
  - cp ../target/SmartApplianceEnabler*.war sae-ci/SmartApplianceEnabler.war
  - docker build --tag=avanux/smartapplianceenabler-amd64:ci ./sae-ci
  - docker push avanux/smartapplianceenabler-amd64:ci
dist: bionic
sudo: required
jdk:
  - openjdk11
before_install:
  - sudo apt-get -y install ccrypt
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - unzip -qq apache-maven-3.3.9-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH
  - wget https://nodejs.org/dist/v10.17.0/node-v10.17.0-linux-x64.tar.gz
  - tar xfz node-v10.17.0-linux-x64.tar.gz
  - export PATH=$PWD/node-v10.17.0-linux-x64/bin:$PATH
after_success:
  - bash <(curl -s https://codecov.io/bash)
